#!/bin/bash

# Import variables
. /home/sanickiosk/sanickiosk/config/browser.cfg

echo "
Opera Preferences version 2.1
; Do not edit this file while Opera is running
; This file is stored in UTF-8 encoding
" > /home/kiosk/.opera/operaprefs.ini

# Empty cache when exiting
if [ $empty_on_exit = "True" ]
then
	echo "
[Disk Cache]
Empty On Exit=1
	" >> /home/kiosk/.opera/operaprefs.ini
fi

echo "
[State]
Accept License=1

[User Prefs]
Auto Dropdown=0
Keyboard Configuration=/home/kiosk/.opera/keyboard/sanickiosk_keyboard.ini
Toolbar Configuration=/home/kiosk/.opera/toolbar/sanickiosk_toolbar.ini
Speed Dial State=2
Show Startup Dialog=0
Show Crash Log Upload Dialog=0
Show Problem Dialog=0
" >> /home/kiosk/.opera/operaprefs.ini

# Delete cookies when exiting
if [ $accept_cookies_session_only = "True" ]
then
	echo "
Accept Cookies Session Only=1
	" >> /home/kiosk/.opera/operaprefs.ini
fi

# Disable opera:config
if [ $disable_config_url = "True" ]
then
	echo "
Enable config URL=false
	" >> /home/kiosk/.opera/operaprefs.ini
fi

# Custom User-Agent
if [ "$custom_user_agent" != "None" ]
then
	echo Custom User-Agent=$custom_user_agent >> /home/kiosk/.opera/operaprefs.ini
fi

# Set Home Page
if [ $kioskspeeddial = "False" ]
then
	echo "Startup Type=2" >> /home/kiosk/.opera/operaprefs.ini
	home="Home URL="$home_url
	echo $home >> /home/kiosk/.opera/operaprefs.ini
else
	echo "
Startup Type=4
Speed Dial State=2
Home URL=
	" >> /home/kiosk/.opera/operaprefs.ini
fi
