#! /bin/sh

path=`find /home/ -name "sanickiosk_splash.png"`

do_start () {
    /usr/bin/fbi -T 1 -noverbose -a $path
    exit 0
}

case "$1" in
  start)
    do_start
    ;;
  restart|reload|force-reload)
    echo "You can't do that" >&2
    exit 3No-op
    ;;
  stop)
    # Nothing here. Move on.
    ;;
  status)
    exit 0
    ;;
  *)
    echo "Script to show splash screen " >&2
    exit 3
    ;;
esac

:
