#! /bin/sh

### BEGIN INIT INFO
# Provides:          aaa_splashscreen
# Required-Start:
# Required-Stop:
# Should-Start:
# Default-Start:     S
# Default-Stop:
# Short-Description: Show custom splashscreen
# Description:       Show custom splashscreen
### END INIT INFO

path=`find /home/ -name "sanickiosk_splash.png"`

do_start () {

    /usr/bin/fbi -timeout 20 -a -noverbose $path
    exit 0
}

case "$1" in
  start|"")
    do_start
    ;;
  restart|reload|force-reload)
    echo "Error: argument '$1' not supported" >&2
    exit 3
    ;;
  stop)
    # No-op
    ;;
  status)
    exit 0
    ;;
  *)
    echo "Usage: aaa_splashscreen [start|stop]" >&2
    exit 3
    ;;
esac

:
